name: Release workflow

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:        
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install zip
        uses: montudor/action-zip@v1
      - name: Build
        run: ./build.sh
      - name: Get version
        id: version
        uses: notiz-dev/github-action-json-property@release
        with: 
            path: 'manifest.json'
            prop_path: 'version'
      - name: Get current version
        uses: actions-ecosystem/action-get-latest-tag@v1
        id: latest_version
      - name: Verify new version
        if: ${{ steps.version.outputs.prop <= steps.latest_version.outputs.tag }}
        uses: actions/github-script@v3
        with:
          script: |
              core.setFailed('New version ${{ steps.version.outputs.prop }} should be greated than old version ${{ steps.latest_version.outputs.tag }}')
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          generate_release_notes: true
          fail_on_unmatched_files: true
          name: ${{ steps.version.outputs.prop }}
          tag_name: ${{ steps.version.outputs.prop }}
          files: |
            firefox.zip
            chrome.zip
