name: Release workflow

on:
  push:
    branches:
      - master

jobs:        
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Zip chrome
        uses: montudor/action-zip@v1
        with:
          args: zip -r ./chrome.zip ./* -x .gitignore -x .github -x .git -x *.zip
      - name: Change manifest version
        uses: jacobtomlinson/gha-find-replace@v2
        with:
          include: 'manifest.json'
          find: '"manifest_version": 3,'
          replace: '"manifest_version": 2,'
          regex: false
      - name: Change host_permissions
        uses: jacobtomlinson/gha-find-replace@v2
        with:
          include: 'manifest.json'
          find: 'host_permissions'
          replace: 'permissions'
          regex: false
      - name: Zip firefox
        uses: montudor/action-zip@v1
        with:
          args: zip -r ./firefox.zip ./* -x .gitignore -x .github -x .git -x *.zip
  
      - name: Get new version
        id: new_version
        uses: notiz-dev/github-action-json-property@release
        with: 
            path: 'manifest.json'
            prop_path: 'version'
      - name: Get current version
        uses: actions-ecosystem/action-get-latest-tag@v1
        id: latest_version
      - name: Verify new version
        if: ${{ steps.new_version.outputs.prop <= steps.latest_version.outputs.tag }}
        uses: actions/github-script@v3
        with:
          script: |
              core.setFailed('New version ${{ steps.new_version.outputs.prop }} should be greated than old version ${{ steps.latest_version.outputs.tag }}')
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          generate_release_notes: true
          fail_on_unmatched_files: true
          name: ${{ steps.new_version.outputs.prop }}
          tag_name: ${{ steps.new_version.outputs.prop }}
          files: |
            firefox.zip
            chrome.zip
